name: Deploy to Backend to Firebase Cloud on merge
on:
  push:
    branches:
      - develop
    paths:
      - "backend/**"

env:
  PROJECT_ID: "test-project-daliborr-dev"

jobs:
  build-and-deploy-cloud-functions:
    name: Firebase build backend and deploy
    runs-on: ubuntu-latest
    env:
      working-directory: "backend"
      functions-directory: "backend/functions"
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ env.functions-directory }}/.nvmrc

      - name: Install dependencies
        working-directory: ${{ env.functions-directory }}
        run: npm ci

      - name: Deploy cloud functions to Firebase
        uses: w9jds/firebase-action@v13.16.0
        with:
          args: deploy --only firestore:rules,storage
        env:
          PROJECT_PATH: "./backend"
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_PROJECT_DALIBORR_DEV }}
